

spring:

    datasource:
        url: jdbc:mysql://localhost:3306/uniforms_system?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 597169477
    http:
      encoding:
        charset: utf-8
        force-request: true
        enabled: true
        force: true
        force-response: true


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: yidong.model


server:
  address: 0.0.0.0
  port: 8080






